#!/usr/bin/env bash
# Start an Ethereum client using a database generated by generate-state.sh.
#
# Usage:
#   ./scripts/start-client.sh geth               # start geth
#   ./scripts/start-client.sh erigon              # start erigon
#   ./scripts/start-client.sh besu                # start besu
#   ./scripts/start-client.sh --help              # show all options
#
# Environment variables (override defaults):
#   OUTDIR        Directory containing client datadirs   (default: ./data)
#   CHAIN_ID      Chain ID                               (default: 1337)
#   HTTP_PORT     HTTP-RPC port                           (default: 8545)
#   WS_PORT       WebSocket port                          (default: 8546)
#   AUTHRPC_PORT  Engine API port                         (default: 8551)
#   P2P_PORT      P2P listen port                         (default: 30303)
#   LOG_LEVEL     Log verbosity                           (default: 3 / INFO)
#
# Client binaries:
#   By default, the script looks for the binary in PATH. Override with:
#   GETH_BIN      Path to geth binary     (default: geth or ../clients/go-ethereum/build/bin/geth)
#   ERIGON_BIN    Path to erigon binary   (default: erigon or ../clients/erigon/build/bin/erigon)
#   BESU_BIN      Path to besu binary     (default: besu or ../clients/besu/build/install/besu/bin/besu)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CLIENTS_DIR="$(dirname "$ROOT_DIR")/clients"

# Defaults
OUTDIR="${OUTDIR:-$ROOT_DIR/data}"
CHAIN_ID="${CHAIN_ID:-1337}"
HTTP_PORT="${HTTP_PORT:-8545}"
WS_PORT="${WS_PORT:-8546}"
AUTHRPC_PORT="${AUTHRPC_PORT:-8551}"
P2P_PORT="${P2P_PORT:-30303}"
LOG_LEVEL="${LOG_LEVEL:-3}"

GETH_BIN="${GETH_BIN:-}"
ERIGON_BIN="${ERIGON_BIN:-}"
BESU_BIN="${BESU_BIN:-}"
NETHERMIND_BIN="${NETHERMIND_BIN:-}"

log() { echo "[$(date +%H:%M:%S)] $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

show_help() {
    head -26 "$0" | tail -24
    exit 0
}

# Resolve a client binary: check explicit var, then PATH, then clients/ dir.
find_bin() {
    local name=$1
    local explicit=$2
    local path_name=$3
    local clients_path=$4

    if [ -n "$explicit" ]; then
        if [ -x "$explicit" ]; then
            echo "$explicit"
            return
        fi
        die "$name binary not found at $explicit"
    fi

    if command -v "$path_name" &>/dev/null; then
        command -v "$path_name"
        return
    fi

    if [ -x "$clients_path" ]; then
        echo "$clients_path"
        return
    fi

    die "$name binary not found. Install it, add to PATH, or set ${name^^}_BIN"
}

# ============================================================
# Parse arguments
# ============================================================
if [ $# -eq 0 ]; then
    echo "Usage: $0 <client> [--help]"
    echo "Clients: geth, erigon, besu, nethermind"
    exit 1
fi

CLIENT=""
EXTRA_ARGS=()

for arg in "$@"; do
    case "$arg" in
        --help|-h)
            show_help
            ;;
        geth|erigon|besu|nethermind)
            CLIENT="$arg"
            ;;
        *)
            EXTRA_ARGS+=("$arg")
            ;;
    esac
done

if [ -z "$CLIENT" ]; then
    die "No client specified. Choose: geth, erigon, besu, nethermind"
fi

# ============================================================
# Verify the database exists
# ============================================================
case "$CLIENT" in
    geth)
        DB_PATH="$OUTDIR/geth/geth/chaindata"
        [ -d "$DB_PATH" ] || die "Geth database not found at $DB_PATH. Run generate-state.sh first."
        ;;
    erigon)
        DB_PATH="$OUTDIR/erigon"
        [ -d "$DB_PATH" ] || die "Erigon database not found at $DB_PATH. Run generate-state.sh first."
        ;;
    besu)
        DB_PATH="$OUTDIR/besu"
        [ -d "$DB_PATH" ] || die "Besu database not found at $DB_PATH. Run generate-state.sh first."
        ;;
    nethermind)
        DB_PATH="$OUTDIR/nethermind"
        [ -d "$DB_PATH" ] || die "Nethermind database not found at $DB_PATH. Run generate-state.sh first."
        ;;
esac

GENESIS="$OUTDIR/genesis.json"

# ============================================================
# Generate JWT secret for Engine API (shared across clients)
# ============================================================
JWT_SECRET="$OUTDIR/jwt.hex"
if [ ! -f "$JWT_SECRET" ]; then
    log "Generating JWT secret..."
    openssl rand -hex 32 > "$JWT_SECRET"
fi

# ============================================================
# Start the client
# ============================================================
case "$CLIENT" in
    geth)
        BIN=$(find_bin "geth" "$GETH_BIN" "geth" "$CLIENTS_DIR/go-ethereum/build/bin/geth")
        log "Starting geth from $OUTDIR/geth"
        log "  HTTP-RPC: http://localhost:$HTTP_PORT"
        log "  Binary:   $BIN"

        exec "$BIN" \
            --datadir "$OUTDIR/geth" \
            --state.scheme hash \
            --networkid "$CHAIN_ID" \
            --http --http.addr 0.0.0.0 --http.port "$HTTP_PORT" \
            --http.api eth,web3,net,debug,txpool \
            --http.corsdomain "*" \
            --ws --ws.addr 0.0.0.0 --ws.port "$WS_PORT" \
            --ws.api eth,web3,net,debug,txpool \
            --authrpc.port "$AUTHRPC_PORT" \
            --authrpc.jwtsecret "$JWT_SECRET" \
            --port "$P2P_PORT" \
            --nodiscover \
            --verbosity "$LOG_LEVEL" \
            "${EXTRA_ARGS[@]+"${EXTRA_ARGS[@]}"}"
        ;;

    erigon)
        BIN=$(find_bin "erigon" "$ERIGON_BIN" "erigon" "$CLIENTS_DIR/erigon/build/bin/erigon")
        log "Starting erigon from $OUTDIR/erigon"
        log "  HTTP-RPC: http://localhost:$HTTP_PORT"
        log "  Binary:   $BIN"

        # Erigon needs a genesis file to know the chain config
        [ -f "$GENESIS" ] || die "Genesis file not found at $GENESIS"

        exec "$BIN" \
            --datadir "$OUTDIR/erigon" \
            --networkid "$CHAIN_ID" \
            --http --http.addr 0.0.0.0 --http.port "$HTTP_PORT" \
            --http.api eth,web3,net,debug,txpool \
            --http.corsdomain "*" \
            --ws --ws.port "$WS_PORT" \
            --authrpc.port "$AUTHRPC_PORT" \
            --authrpc.jwtsecret "$JWT_SECRET" \
            --port "$P2P_PORT" \
            --nodiscover \
            --log.console.verbosity "$LOG_LEVEL" \
            "${EXTRA_ARGS[@]+"${EXTRA_ARGS[@]}"}"
        ;;

    besu)
        BIN=$(find_bin "besu" "$BESU_BIN" "besu" "$CLIENTS_DIR/besu/build/install/besu/bin/besu")
        log "Starting besu from $OUTDIR/besu"
        log "  HTTP-RPC: http://localhost:$HTTP_PORT"
        log "  Binary:   $BIN"

        [ -f "$GENESIS" ] || die "Genesis file not found at $GENESIS"

        # Map numeric log level to Besu log levels
        case "$LOG_LEVEL" in
            0|1) BESU_LOG="ERROR" ;;
            2)   BESU_LOG="WARN" ;;
            3)   BESU_LOG="INFO" ;;
            4)   BESU_LOG="DEBUG" ;;
            *)   BESU_LOG="TRACE" ;;
        esac

        exec "$BIN" \
            --data-path "$OUTDIR/besu" \
            --genesis-file "$GENESIS" \
            --network-id "$CHAIN_ID" \
            --data-storage-format=FOREST \
            --genesis-state-hash-cache-enabled=true \
            --rpc-http-enabled --rpc-http-host 0.0.0.0 --rpc-http-port "$HTTP_PORT" \
            --rpc-http-api ETH,WEB3,NET,DEBUG,TXPOOL \
            --rpc-http-cors-origins="*" \
            --rpc-ws-enabled --rpc-ws-host 0.0.0.0 --rpc-ws-port "$WS_PORT" \
            --rpc-ws-api ETH,WEB3,NET,DEBUG,TXPOOL \
            --engine-rpc-port "$AUTHRPC_PORT" \
            --engine-jwt-secret "$JWT_SECRET" \
            --p2p-port "$P2P_PORT" \
            --p2p-enabled=false \
            --logging="$BESU_LOG" \
            "${EXTRA_ARGS[@]+"${EXTRA_ARGS[@]}"}"
        ;;

    nethermind)
        nm_dll="$CLIENTS_DIR/nethermind/src/Nethermind/artifacts/bin/Nethermind.Runner/release/nethermind.dll"
        dotnet_bin="${DOTNET_BIN:-dotnet}"

        # Try native binary first, fall back to dotnet <dll>
        if [ -n "$NETHERMIND_BIN" ] && [ -x "$NETHERMIND_BIN" ]; then
            BIN="$NETHERMIND_BIN"
        elif command -v nethermind &>/dev/null; then
            BIN=$(command -v nethermind)
        elif [ -f "$nm_dll" ]; then
            # Prefer dotnet <dll> — avoids .NET runtime resolution issues
            BIN="DOTNET_DLL"
        else
            die "Nethermind binary not found. Build it or set NETHERMIND_BIN"
        fi

        log "Starting nethermind from $OUTDIR/nethermind"
        log "  HTTP-RPC: http://localhost:$HTTP_PORT"

        NETHERMIND_CHAINSPEC="$OUTDIR/nethermind-chainspec.json"
        [ -f "$NETHERMIND_CHAINSPEC" ] || die "Nethermind chainspec not found at $NETHERMIND_CHAINSPEC"

        # Map numeric log level to Nethermind log levels
        case "$LOG_LEVEL" in
            0|1) NM_LOG="ERROR" ;;
            2)   NM_LOG="WARN" ;;
            3)   NM_LOG="INFO" ;;
            4)   NM_LOG="DEBUG" ;;
            *)   NM_LOG="TRACE" ;;
        esac

        NM_ARGS=(
            --data-dir "$OUTDIR/nethermind"
            --config none
            --Init.BaseDbPath "$OUTDIR/nethermind/nethermind_db"
            --Init.ChainSpecPath "$NETHERMIND_CHAINSPEC"
            --Init.DiscoveryEnabled false
            --Init.PeerManagerEnabled false
            --Network.P2PPort "$P2P_PORT"
            --Network.DiscoveryPort "$P2P_PORT"
            --JsonRpc.Enabled true
            --JsonRpc.Host 0.0.0.0
            --JsonRpc.Port "$HTTP_PORT"
            --JsonRpc.EnabledModules "[Eth,Web3,Net,Debug,TxPool]"
            --JsonRpc.WebSocketsPort "$WS_PORT"
            --JsonRpc.EnginePort "$AUTHRPC_PORT"
            --JsonRpc.EngineHost 127.0.0.1
            --JsonRpc.JwtSecretFile "$JWT_SECRET"
            --HealthChecks.LowStorageSpaceWarningThreshold 0
            --HealthChecks.LowStorageSpaceShutdownThreshold 0
            --log "$NM_LOG"
            "${EXTRA_ARGS[@]+"${EXTRA_ARGS[@]}"}"
        )

        if [ "$BIN" = "DOTNET_DLL" ]; then
            log "  Binary:   $dotnet_bin $nm_dll"
            exec "$dotnet_bin" "$nm_dll" "${NM_ARGS[@]}"
        else
            log "  Binary:   $BIN"
            exec "$BIN" "${NM_ARGS[@]}"
        fi
        ;;
esac
